"""add skill slug

Revision ID: 5b9ef9025c64
Revises: c7e2f91a4b6d
Create Date: 2026-09-19 13:56:16.711310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9ef9025c64'
down_revision: Union[str, Sequence[str], None] = 'c7e2f91a4b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('slug', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_column('skills', 'slug')
    # ### end Alembic commands ###
